"""add cascade delete to chat_messages fk

Revision ID: c0f7cc8265bd
Revises: 63fd1ad266ed
Create Date: 2026-07-08 00:34:06.307414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f7cc8265bd'
down_revision: Union[str, None] = '63fd1ad266ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_messages_conversation_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_conversation_id_fkey', 'chat_messages', 'chat_conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###
